name: pull-request-trigger

on:
  pull_request:
    branches: [ main, master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send request to server
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bd4c-192-38-10-18.ngrok.io'
        method: 'POST'
        data: '{ "repository": "${{ github.repository }}", "branch": "${{ github.head_ref }}" }'
